name: CI/CD Pipeline

on: 
    push: 
        branches: 
            - main # when pushing changes to main branch

    pull_request:
        branches: 
            - main # when creating PRs against main branch


jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            
            - name: setup go
              uses: actions/setup-go@v5
              with: 
                 go-version: '1.23.2'

            - name: download dependencies 
              run: go mod download

            - name: build server 
              run: go build ./cmd/main.go

            - name: run tests
              id: run_tests
              run: 
                echo "Running test cases..."
                go test ./...
            
            - name: check tests status
              run: |
                if [ "${{ steps.run_tests.result }}" == "success" ]; then 
                    echo TESTS SUCCESS
                else 
                    echo SOME TESTS FAILED, check logs....
                    exit 1
                fi
               


            

   # deploy: 



